[package]
name = "socket_chat"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"

[dependencies]
anyhow = "1.0.94"
ratatui = "0.29.0"
serde = "1.0.216"
